<a href="https://colab.research.google.com/github/UtkarshTyagiisgoated/E22/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import models, layers
from tensorflow.keras.datasets import mnist
import numpy
from tensorflow.keras.utils import to_categorical

In [70]:
(train_images,train_labels), (test_images, test_labels) = mnist.load_data()

In [71]:
train_images[0].max()

255

In [72]:
train_images = train_images.astype('float32')/255
test_images = test_images.astype('float32')/255

In [73]:
train_images.shape

(60000, 28, 28)

In [74]:
train_images = train_images.reshape(train_images.shape[0],28,28,1)
test_images = test_images.reshape(test_images.shape[0],28,28,1)

In [75]:
train_images[0].shape

(28, 28, 1)

In [76]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [77]:
data_augumentation = tf.keras.Sequential([
    layers.RandomRotation(0.1),
    layers.RandomFlip(),
    layers.RandomZoom(0.1),
    layers.RandomTranslation(0.1,0.1)
])

In [78]:
def create_model():
    inputs = keras.Input(shape=(28,28,1))
    x = data_augumentation(inputs)

    x = keras.layers.Conv2D(32,3, activation="relu", padding="same")(x)
    x = keras.layers.BatchNormalization()(x)
    x = keras.layers.MaxPool2D(2)(x)
    x = keras.layers.SpatialDropout2D(0.2)(x)

    x = keras.layers.Conv2D(64,3, activation="relu", padding="same")(x)
    x = keras.layers.BatchNormalization()(x)
    x = keras.layers.Conv2D(64,3, activation="relu", padding="same")(x)
    x = keras.layers.MaxPool2D(2)(x)
    x = keras.layers.SpatialDropout2D(0.2)(x)

    residual = x
    x = keras.layers.Conv2D(64,3, activation="relu", padding="same")(x)
    x = keras.layers.BatchNormalization()(x)
    x = keras.layers.Conv2D(64,3, activation="relu", padding="same")(x)
    x = keras.layers.BatchNormalization()(x)
    x = keras.layers.add([x, residual])

    x = keras.layers.GlobalAveragePooling2D()(x)
    x = keras.layers.Dense(256, activation="relu")(x)
    outputs = keras.layers.Dense(10, activation="softmax")(x)

    model = keras.Model(inputs, outputs)
    return model





In [79]:
model = create_model()

In [80]:
from keras.optimizers import Adam

In [81]:
model.compile(optimizer = Adam(learning_rate=0.001), loss = "sparse_categorical_crossentropy", metrics = ['accuracy'])

In [82]:
history = model.fit(train_images, train_labels, epochs=50)


Epoch 1/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 31s 13ms/step - accuracy: 0.5899 - loss: 1.1351
Epoch 2/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 37s 11ms/step - accuracy: 0.8757 - loss: 0.3705
Epoch 3/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.8998 - loss: 0.2999
Epoch 4/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 22s 10ms/step - accuracy: 0.9113 - loss: 0.2629
Epoch 5/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9175 - loss: 0.2458
Epoch 6/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 22s 10ms/step - accuracy: 0.9227 - loss: 0.2342
Epoch 7/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9267 - loss: 0.2186
Epoch 8/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 24s 12ms/step - accuracy: 0.9287 - loss: 0.2139
Epoch 9/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 38s 10ms/step - accuracy: 0.9313 - loss: 0.2033
Epoch 10/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.9330 - loss: 0.1947
Epoch 11/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 22s 10ms/step - accuracy: 0.9349 - loss: 0.1947
Epoch 12

In [100]:
import joblib

In [84]:
joblib.dump(model, "model.pkl")

['model.pkl']

In [85]:
y_pred = model.predict(test_images).argmax(axis =1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [86]:
y_pred


array([7, 2, 1, ..., 4, 5, 6])

In [87]:
from sklearn.metrics import classification_report

In [88]:
import pprint

In [89]:
pprint.pprint(classification_report(y_pred, test_labels))

('              precision    recall  f1-score   support\n'
 '\n'
 '           0       0.99      0.99      0.99       981\n'
 '           1       0.99      0.99      0.99      1131\n'
 '           2       0.91      0.94      0.93       997\n'
 '           3       0.99      0.98      0.99      1019\n'
 '           4       0.99      0.98      0.98       995\n'
 '           5       0.96      0.90      0.93       956\n'
 '           6       0.93      0.93      0.93       959\n'
 '           7       0.98      0.97      0.97      1041\n'
 '           8       0.99      0.99      0.99       972\n'
 '           9       0.91      0.97      0.94       949\n'
 '\n'
 '    accuracy                           0.96     10000\n'
 '   macro avg       0.96      0.96      0.96     10000\n'
 'weighted avg       0.97      0.96      0.96     10000\n')


In [90]:
### New image predictionnn

In [91]:
!pip install pillow

In [92]:
import numpy as np
from PIL import Image

In [93]:
def preprocess_image(image_path):
    # Open the image
    img = Image.open(image_path)

    # Convert to grayscale if it's not already
    if img.mode != 'L':
        img = img.convert('L')

    # Resize to 28x28 pixels
    img = img.resize((28, 28))

    # Convert to numpy array and normalize
    img_array = np.array(img).astype('float32') / 255.0

    # Reshape to (1, 28, 28, 1) for model input
    img_array = img_array.reshape(1, 28, 28, 1)

    return img_array

In [94]:
def predict_image(model, img_array):
    prtediction = model.predict(img_array)
    class_index = np.argmax(prtediction)

    class_name = ['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten']
    predicted_class = class_name[class_index]
    confidence = prtediction[0][class_index]
    return predicted_class, confidence

In [134]:
processed_image = preprocess_image("download (6).jpeg")


In [135]:
processed_image

array([[[[0.9137255 ],
         [0.9137255 ],
         [0.9098039 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.91764706],
         [0.91764706],
         [0.9137255 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.92156863],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.92156863],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706]],

        [[0.9098039 ],
         [0.9098039 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.9098039 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.9137255 ],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         [0.91764706],
         

In [136]:
predicted_class, confidence = predict_image(model, processed_image)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [137]:
predicted_class

'four'

In [138]:
confidence

0.8693812